INSERT INTO users (userId, username) VALUES (1, 'Test1');
INSERT INTO users (userId, username) VALUES (2, 'Test2');
INSERT INTO users (userId, username) VALUES (3, 'Test3');
INSERT INTO users (userId, username) VALUES (4, 'Test4');
INSERT INTO users (userId, username) VALUES (5, 'Test5');
INSERT INTO users (userId, username) VALUES (6, 'Test6');
INSERT INTO users (userId, username) VALUES (7, 'Test7');
INSERT INTO users (userId, username) VALUES (8, 'Test8');
INSERT INTO users (userId, username) VALUES (9, 'Test9');